### ISSUE TITLE
conflicts with pymol

### ISSUE THREAD

**Issue by wangjiawen2013** [prody/ProDy#2129]
Hi,
pymol 3.1.0 requires numpy>=1.26.4, while prody 2.4.1 requires numpy<1.24,>=1.10. Since the latest numpy is 2.2.0 now, Could you upgrade the numpy version that prody requires ?

**Comment by jamesmkrieger** [comment]
We have fixed this but are still in the process of making a release of ProDy 2.5.0 - in the meantime, please use the development version from github

pip install -U git+https://github.com/prody/prody.git@main

**Comment by jamesmkrieger** [comment]
Please let confirm if this solves the issue

**Comment by wangjiawen2013** [comment]
I failed to install ProDy using `pip install -U git+https://github.com/prody/prody.git@main` on my windows11 laptop. I'll try again next month, we'll buy a linux server.

**Comment by jamesmkrieger** [comment]
Have you tried using the windows subsystem for Linux WSL2g? It works fine there for me

**Comment by BartoszJanuszNA** [comment]
> We have fixed this but are still in the process of making a release of ProDy 2.5.0 - in the meantime, please use the development version from github
> 
> pip install -U git+https://github.com/prody/prody.git@main

Hi! On main branch I can still see numpy pinned to `<2`. Can I safely remove this limit? (I can use my fork for now).

**Comment by jamesmkrieger** [comment]
Yes. When we manage to release it
